feat: add deployment trigger input (optional)
go-fjords/cloudflare-delete-deployments-action pull request #25
Opened 2022-11-17 11:29 UTC by zaosoula

2022-12-16 08:19 UTC, snorremd commented
Oh, this is nice! Sorry I did not see the PR before now. I will take a closer look at my earliest convenience and see if I cannot get this merged. 👍

2022-12-16 12:08 UTC, snorremd commented on main.js
> -    .slice(1)
> @snorremd We tried to understand but didn't find any reason for removing the first result of the branchDeployments, if you can provide us an explenation

Back when I made this action you had to keep at least one deployment for any given alias. Trying to delete the last deployment for a given alias would result in an error. Not sure if this is still true.

The slice is used to remove the last deployment id for the alias from the deletion list.

2022-12-16 12:15 UTC, snorremd requested changes
I like the use case where `ad_hoc` deployments can be supported. Nice fix for the rate limit issue.

I'm going to have to check if the removal of the slice will be an issue or if Cloudflare has removed the limitation of not deleting all deploys for a given alias.

Some unit tests are also failing.

2022-12-16 12:15 UTC, snorremd commented on main.js
> +    await wait(250); // Api rate limit is 1200req/5min <--> 4req/s
This is useful, thanks! 👍

2022-12-16 12:15 UTC, snorremd commented on main.js
> +    .filter(d =>  d.deployment_trigger.type === deploymentTriggerType)
Cool, it is nice to support this usecase. 👍

2022-12-16 12:15 UTC, snorremd commented on main.test.js
> +    {
The original test was checking for the slice due to the way Cloudflare requires (required?) at least one deployment to remain for a given alias. Will check if this is still the case.

2022-12-27 14:24 UTC, zaosoula commented on main.test.js
> +    {
@snorremd Were you able to test if Cloudflare still needs one deployment per alias ?

2023-01-02 11:35 UTC, snorremd commented on main.test.js
> +    {
I tested deleting via the Cloudflare UI now and it seems it is possible to delete all deployments. If you delete a deployment for an alias with a single deployment left it triggers a warning.  I will check if the API accepts deleations as well. :)

2023-01-02 12:00 UTC, snorremd commented on main.test.js
> +    {
It seems deleting the last deployment requires a `?force=true` parameter in the request. See errror response from API:

```json
{
  "result": null,
  "success": false,
  "errors": [
    {
      "code": 8000035,
      "message": "You cannot delete an aliased deployment without a `?force=true` parameter in the API request URL."
    }
  ],
  "messages": []
}
```

I think the best solution here is to add a new parameter to specify how many deployments you want to keep. It should then delete all but the `N` latest deployments (ordered by date). What do you think?

If you agree, could you update your PR with a new Github Actions parameter `keep` that accepts a number of deployments to keep. If `keep === 0` add `?force=true` to the request URL. `keep` should probably default to 1 to preserve existing behaviour, though breaking changes at this point isn't so bad since it is still in preview releases.

2023-01-18 12:29 UTC, snorremd commented
Closing this in favour of https://github.com/go-fjords/cloudflare-delete-deployments-action/pull/33. I think I've managed to keep the changes you requested while adding some improvement of my own. Will try to get the other PR merged quickly. As it turns out we need the `ad_hoc` trigger type too.

2023-01-18 12:29 UTC, closed without merging